/**
 * Hand-curated set of globally interesting races. Kept as a collector source so the
 * same normalisation, validation and merge rules apply to it as to the API sources.
 * Fees marked `indicative: true` are ballpark figures — always verify with the organiser.
 */

export const id = 'curated';

const EVENTS = [
  {
    slug: 'berlin-marathon',
    name: 'BMW BERLIN-MARATHON',
    date: '2026-09-27',
    dateStatus: 'confirmed',
    type: 'road',
    distances: ['42.2 km'],
    tags: ['world-marathon-major', 'road', 'fast-course', 'europe'],
    featured: true,
    location: { city: 'Berlin', country: 'Germany', countryCode: 'DE' },
    start: { lat: 52.514444, lon: 13.350278, name: 'Straße des 17. Juni, Tiergarten' },
    fees: [{ amount: 205, currency: 'EUR', indicative: false, label: { en: 'Standard entry (incl. 4-day transport ticket)', pl: 'Pakiet standardowy (z 4-dniowym biletem komunikacji)' } }],
    website: 'https://www.bmw-berlin-marathon.com/en/',
    registrationUrl: 'https://www.bmw-berlin-marathon.com/en/registration/registration-information',
    links: [{ url: 'https://en.wikipedia.org/wiki/Berlin_Marathon', label: { en: 'Wikipedia', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: 'The flattest and fastest of the Marathon Majors — where most marathon world records fall.',
        description: 'Berlin is the world record course: the pancake-flat loop through Tiergarten, Potsdamer Platz and the Brandenburg Gate has produced more marathon world records than any other race. Entry is by lottery (drawn the previous autumn), with charity and tour-operator places as the alternative routes in. Around 55,000 runners start on Straße des 17. Juni and finish under the Brandenburg Gate.',
      },
      pl: {
        summary: 'Najbardziej płaski i najszybszy z Majorsów — tu padają rekordy świata w maratonie.',
        description: 'Berlin to trasa rekordów świata: płaska pętla przez Tiergarten, Potsdamer Platz i Bramę Brandenburską dała więcej rekordów świata w maratonie niż jakikolwiek inny bieg. Wejście odbywa się przez losowanie (rozstrzygane jesienią roku poprzedniego), a alternatywą są pakiety charytatywne i biura podróży. Około 55 000 biegaczy startuje na Straße des 17. Juni, a meta znajduje się pod Bramą Brandenburską.',
      },
    },
  },
  {
    slug: 'chicago-marathon',
    name: 'Bank of America Chicago Marathon',
    date: '2026-10-11',
    dateStatus: 'confirmed',
    type: 'road',
    distances: ['42.2 km'],
    tags: ['world-marathon-major', 'road', 'fast-course', 'north-america'],
    featured: true,
    location: { city: 'Chicago', region: 'Illinois', country: 'United States', countryCode: 'US' },
    start: { lat: 41.874722, lon: -87.620833, name: 'Grant Park' },
    fees: [{ amount: 260, currency: 'USD', indicative: true, label: { en: 'US resident entry', pl: 'Opłata dla mieszkańców USA' } },
           { amount: 295, currency: 'USD', indicative: true, label: { en: 'International entry', pl: 'Opłata międzynarodowa' } }],
    website: 'https://www.chicagomarathon.com/',
    registrationUrl: 'https://www.chicagomarathon.com/runners/frequently-asked-application-questions/',
    links: [{ url: 'https://en.wikipedia.org/wiki/Chicago_Marathon', label: { en: 'Wikipedia', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: 'A flat loop through 29 neighbourhoods with famously loud crowds — over 200,000 people applied for 2026.',
        description: 'Chicago runs a single flat loop out of Grant Park and back, threading 29 city neighbourhoods with near-continuous spectator support. It is the classic first Major for a personal best: the course is fast, the October weather is usually cool, and the finish returns to the lakefront park where the day began. Entry is by lottery, time qualification, charity or tour package.',
      },
      pl: {
        summary: 'Płaska pętla przez 29 dzielnic i legendarny doping — na 2026 rok wpłynęło ponad 200 000 zgłoszeń.',
        description: 'Chicago to jedna płaska pętla z Grant Park i z powrotem, przecinająca 29 dzielnic miasta z niemal nieprzerwanym dopingiem. To klasyczny pierwszy Major na życiówkę: trasa jest szybka, październikowa pogoda zwykle chłodna, a meta wraca do parku nad jeziorem, gdzie zaczyna się bieg. Wejście przez losowanie, minimum czasowe, cele charytatywne lub pakiet turystyczny.',
      },
    },
  },
  {
    slug: 'new-york-city-marathon',
    name: 'TCS New York City Marathon',
    date: '2026-11-01',
    dateStatus: 'confirmed',
    type: 'road',
    distances: ['42.2 km'],
    tags: ['world-marathon-major', 'road', 'iconic', 'north-america'],
    featured: true,
    location: { city: 'New York City', region: 'New York', country: 'United States', countryCode: 'US' },
    start: { lat: 40.605833, lon: -74.056944, name: 'Fort Wadsworth, Staten Island' },
    fees: [{ amount: 333.11, currency: 'USD', indicative: false, label: { en: 'Non-member entry', pl: 'Opłata bez członkostwa NYRR' } },
           { amount: 269.66, currency: 'USD', indicative: false, label: { en: 'NYRR member entry', pl: 'Opłata dla członków NYRR' } }],
    website: 'https://www.nyrr.org/tcsnycmarathon',
    links: [{ url: 'https://en.wikipedia.org/wiki/New_York_City_Marathon', label: { en: 'Wikipedia', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: 'The biggest marathon on earth: five boroughs, five bridges, two million spectators.',
        description: 'New York starts on the Verrazzano-Narrows Bridge above the harbour and crosses all five boroughs before finishing in Central Park. It is the largest marathon in the world by finishers and the loudest — First Avenue after the Queensboro Bridge is a wall of sound. The course is honest rather than fast: the bridges roll, and the final miles climb through Central Park.',
      },
      pl: {
        summary: 'Największy maraton świata: pięć dzielnic, pięć mostów, dwa miliony kibiców.',
        description: 'Nowy Jork startuje na moście Verrazzano-Narrows nad zatoką i przecina wszystkie pięć dzielnic, by zakończyć bieg w Central Parku. To największy maraton świata pod względem liczby biegaczy na mecie i jednocześnie najgłośniejszy — First Avenue za mostem Queensboro to ściana dźwięku. Trasa jest wymagająca, nie szybka: mosty falują, a ostatnie kilometry pną się przez Central Park.',
      },
    },
  },
  {
    slug: 'valencia-marathon',
    name: 'Maratón Valencia Trinidad Alfonso',
    date: '2026-12-06',
    dateStatus: 'confirmed',
    type: 'road',
    distances: ['42.2 km'],
    tags: ['road', 'fast-course', 'europe', 'pb-hunting'],
    featured: true,
    location: { city: 'Valencia', country: 'Spain', countryCode: 'ES' },
    start: { lat: 39.4545, lon: -0.351, name: 'Ciudad de las Artes y las Ciencias' },
    fees: [{ amount: 115, currency: 'EUR', indicative: true, label: { en: 'Standard entry', pl: 'Opłata standardowa' } }],
    website: 'https://www.valenciaciudaddelrunning.com/en/marathon/',
    links: [{ url: 'https://en.wikipedia.org/wiki/Valencia_Marathon', label: { en: 'Wikipedia', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: 'Europe’s fastest non-Major: flat, cool December weather and a finish on a bridge over water.',
        description: 'Valencia has become the personal-best factory of European marathoning — flat, sheltered, run in ideal December temperatures, with pacing groups for every target time. The finish is unique: a blue carpet laid across a footbridge over the lake at the City of Arts and Sciences. Places sell out months ahead, so plan the entry well before autumn.',
      },
      pl: {
        summary: 'Najszybszy europejski maraton spoza Majorsów: płasko, chłodny grudzień i meta na moście nad wodą.',
        description: 'Walencja stała się fabryką życiówek europejskiego maratonu — płasko, osłonięcie od wiatru, idealne grudniowe temperatury i pacemakerzy na każdy czas docelowy. Meta jest wyjątkowa: niebieski dywan rozłożony na kładce nad taflą wody w Mieście Sztuki i Nauki. Pakiety wyprzedają się na miesiące przed biegiem, więc zapisy warto zaplanować jeszcze przed jesienią.',
      },
    },
  },
  {
    slug: 'antarctic-ice-marathon',
    name: 'Antarctic Ice Marathon',
    date: '2026-12-13',
    dateStatus: 'confirmed',
    type: 'road',
    distances: ['42.2 km', '21.1 km'],
    tags: ['extreme', 'bucket-list', 'antarctica', 'cold'],
    featured: true,
    location: { city: 'Union Glacier', country: 'Antarctica', countryCode: 'AQ' },
    start: { lat: -79.766667, lon: -83.266667, name: 'Union Glacier Camp' },
    fees: [{ amount: 24500, currency: 'EUR', indicative: true, label: { en: 'Entry incl. flights from Punta Arenas and camp logistics', pl: 'Pakiet z lotami z Punta Arenas i logistyką obozu' } }],
    website: 'https://www.icemarathon.com/',
    links: [{ url: 'https://icemarathon.com/schedule-and-prices', label: { en: 'Schedule and prices', pl: 'Terminarz i ceny' } }],
    content: {
      en: {
        summary: 'The southernmost marathon on the planet, run at 80° South on snow and ice.',
        description: 'Held at Union Glacier, a few hundred kilometres from the South Pole, this is the only marathon run on the Antarctic mainland interior. Runners fly in from Punta Arenas on a chartered aircraft, sleep in a polar camp and race in temperatures around −20 °C with katabatic wind. The field is capped at around 60 people and the price reflects the flights and camp logistics, not the race itself.',
      },
      pl: {
        summary: 'Najbardziej wysunięty na południe maraton świata, biegany na 80° szerokości południowej po śniegu i lodzie.',
        description: 'Bieg odbywa się na lodowcu Union, kilkaset kilometrów od bieguna południowego, i jest jedynym maratonem rozgrywanym w głębi kontynentu antarktycznego. Zawodnicy lecą czarterem z Punta Arenas, śpią w obozie polarnym i ścigają się w temperaturze około −20 °C przy wietrze katabatycznym. Limit to około 60 osób, a cena wynika z lotów i logistyki obozu, nie z samych zawodów.',
      },
    },
  },
  {
    slug: 'tokyo-marathon',
    name: 'Tokyo Marathon',
    date: '2027-03-07',
    dateStatus: 'confirmed',
    type: 'road',
    distances: ['42.2 km'],
    tags: ['world-marathon-major', 'road', 'asia', 'iconic'],
    featured: true,
    location: { city: 'Tokyo', country: 'Japan', countryCode: 'JP' },
    start: { lat: 35.689444, lon: 139.691667, name: 'Tokyo Metropolitan Government Building, Shinjuku' },
    fees: [{ amount: 16500, currency: 'JPY', indicative: true, label: { en: 'Domestic entry', pl: 'Opłata krajowa' } },
           { amount: 25000, currency: 'JPY', indicative: true, label: { en: 'Overseas entry', pl: 'Opłata zagraniczna' } }],
    website: 'https://www.marathon.tokyo/en/',
    registrationUrl: 'https://www.marathon.tokyo/en/participants/',
    links: [{ url: 'https://www.marathon.tokyo/en/participants/guideline/', label: { en: 'Entry information', pl: 'Informacje o zapisach' } }],
    content: {
      en: {
        summary: 'The most orderly Major: immaculate organisation, deep crowds and a flat, fast city course.',
        description: 'Tokyo runs from the Metropolitan Government Building in Shinjuku past Asakusa’s Kaminarimon gate and the Imperial Palace to a finish near Tokyo Station. Runners consistently rate it the best-organised marathon in the world — aid stations, toilets and crowd control are all handled with a precision no other Major matches. Entry is dominated by a heavily oversubscribed lottery held the previous summer.',
      },
      pl: {
        summary: 'Najbardziej poukładany Major: wzorowa organizacja, gęsty doping i płaska, szybka trasa przez miasto.',
        description: 'Tokio startuje przy Budynku Rządu Metropolitalnego w Shinjuku i prowadzi obok bramy Kaminarimon w Asakusie oraz Pałacu Cesarskiego do mety w okolicy Dworca Tokijskiego. Biegacze regularnie oceniają go jako najlepiej zorganizowany maraton świata — punkty odżywcze, toalety i obsługa tłumu działają z precyzją, której nie dorównuje żaden inny Major. Wejście odbywa się głównie przez wielokrotnie przewyższone losowanie latem roku poprzedniego.',
      },
    },
  },
  {
    slug: 'boston-marathon',
    name: 'Boston Marathon',
    date: '2027-04-19',
    dateStatus: 'estimated',
    type: 'road',
    distances: ['42.2 km'],
    tags: ['world-marathon-major', 'road', 'qualifier-only', 'north-america', 'historic'],
    featured: true,
    location: { city: 'Hopkinton to Boston', region: 'Massachusetts', country: 'United States', countryCode: 'US' },
    start: { lat: 42.228611, lon: -71.522778, name: 'Main Street, Hopkinton' },
    fees: [{ amount: 250, currency: 'USD', indicative: true, label: { en: 'US entry', pl: 'Opłata dla biegaczy z USA' } },
           { amount: 285, currency: 'USD', indicative: true, label: { en: 'International entry', pl: 'Opłata międzynarodowa' } }],
    website: 'https://www.baa.org/races/boston-marathon/',
    registrationUrl: 'https://www.baa.org/races/boston-marathon/qualify/',
    links: [{ url: 'https://en.wikipedia.org/wiki/Boston_Marathon', label: { en: 'Wikipedia', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: 'The oldest annual marathon in the world — and the one you have to earn with a qualifying time.',
        description: 'Run every Patriots’ Day since 1897, Boston is a point-to-point course from rural Hopkinton to Boylston Street in the city. The profile is deceptive: a fast downhill opening that wrecks quads, then the Newton hills and Heartbreak Hill after 30 km. Almost all entries require a qualifying time, and in recent years the standard alone has not been enough — a cushion under the qualifier is needed. The date shown is the expected Patriots’ Day; confirm with the B.A.A.',
      },
      pl: {
        summary: 'Najstarszy cyklicznie rozgrywany maraton świata — i jedyny Major, na który trzeba wybiegać minimum.',
        description: 'Rozgrywany w każdy Dzień Patriotów od 1897 roku Boston to trasa z punktu do punktu: z wiejskiego Hopkinton na Boylston Street w centrum miasta. Profil jest zdradliwy: szybki zbieg na starcie niszczy uda, a po 30. kilometrze czekają wzniesienia Newton i Heartbreak Hill. Niemal wszystkie miejsca wymagają minimum czasowego, a w ostatnich latach samo minimum nie wystarczało — potrzebny jest zapas. Podana data to spodziewany Dzień Patriotów; potwierdź ją u organizatora B.A.A.',
      },
    },
  },
  {
    slug: 'london-marathon',
    name: 'TCS London Marathon',
    date: '2027-04-24',
    endDate: '2027-04-25',
    dateStatus: 'confirmed',
    type: 'road',
    distances: ['42.2 km'],
    tags: ['world-marathon-major', 'road', 'europe', 'charity'],
    featured: true,
    location: { city: 'London', country: 'United Kingdom', countryCode: 'GB' },
    start: { lat: 51.4695, lon: 0.0088, name: 'Blackheath, Greenwich' },
    fees: [{ amount: 79.99, currency: 'GBP', indicative: true, label: { en: 'UK ballot entry', pl: 'Opłata z losowania (UK)' } },
           { amount: 185, currency: 'GBP', indicative: true, label: { en: 'International ballot entry', pl: 'Opłata z losowania (międzynarodowa)' } }],
    website: 'https://www.londonmarathonevents.co.uk/london-marathon',
    links: [{ url: 'https://en.wikipedia.org/wiki/London_Marathon', label: { en: 'Wikipedia', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: 'The world’s greatest fundraising race — and in 2027 it runs across two days for the first time.',
        description: 'London goes from Blackheath through Greenwich, over Tower Bridge and along the Embankment to a finish on The Mall. It raises more money for charity than any other single-day sporting event on earth, and the costume-and-crowd atmosphere is unmatched. The 2027 edition is a one-off two-day format across Saturday 24 and Sunday 25 April, taking the field to roughly 100,000 runners.',
      },
      pl: {
        summary: 'Największy charytatywny bieg świata — a w 2027 roku po raz pierwszy rozegrany przez dwa dni.',
        description: 'Londyn prowadzi z Blackheath przez Greenwich, przez Tower Bridge i wzdłuż Embankment do mety na The Mall. Zbiera na cele charytatywne więcej niż jakiekolwiek inne jednodniowe wydarzenie sportowe na świecie, a atmosfera przebrań i dopingu nie ma sobie równych. Edycja 2027 to jednorazowy format dwudniowy w sobotę 24 i niedzielę 25 kwietnia, co podnosi limit do około 100 000 biegaczy.',
      },
    },
  },
  {
    slug: 'comrades-marathon',
    name: 'Comrades Marathon',
    date: '2027-06-13',
    dateStatus: 'confirmed',
    type: 'ultra',
    distances: ['~89 km'],
    tags: ['ultra', 'road', 'africa', 'historic', 'bucket-list'],
    featured: true,
    location: { city: 'Pietermaritzburg / Durban', country: 'South Africa', countryCode: 'ZA' },
    start: { lat: -29.600556, lon: 30.379444, name: 'Pietermaritzburg City Hall (direction alternates yearly)' },
    fees: [{ amount: 250, currency: 'USD', indicative: true, label: { en: 'International entry', pl: 'Opłata międzynarodowa' } }],
    website: 'https://comrades.com/',
    registrationUrl: 'https://enter.comrades.com/comrades-2027',
    links: [{ url: 'https://comrades.com/blogs/the-greatest-story-ever-run-comrades-marathon-launches-2027-centenary-edition', label: { en: '2027 centenary edition', pl: 'Edycja stulecia 2027' } }],
    content: {
      en: {
        summary: '“The Ultimate Human Race”: ~89 km between Durban and Pietermaritzburg, with a 12-hour cut-off. 2027 is the centenary edition.',
        description: 'Comrades is the world’s largest and oldest ultramarathon, run since 1921 between Durban and Pietermaritzburg. The direction alternates each year — the “up run” climbs about 800 m net, the “down run” punishes the quads instead. A hard 12-hour cut-off is enforced by a gunshot at the finish line, and roughly 20,000 runners take the start. The 2027 race is the centenary edition.',
      },
      pl: {
        summary: '„Najtrudniejszy bieg świata”: ~89 km między Durbanem a Pietermaritzburgiem, limit 12 godzin. 2027 to edycja stulecia.',
        description: 'Comrades to największy i najstarszy ultramaraton świata, rozgrywany od 1921 roku między Durbanem a Pietermaritzburgiem. Kierunek zmienia się co roku — „up run” oznacza około 800 m przewyższenia netto, „down run” niszczy za to mięśnie czworogłowe. Twardy limit 12 godzin egzekwowany jest wystrzałem na mecie, a na starcie staje około 20 000 biegaczy. Bieg w 2027 roku to edycja stulecia.',
      },
    },
  },
  {
    slug: 'utmb-mont-blanc',
    name: 'UTMB Mont-Blanc',
    date: '2027-08-27',
    endDate: '2027-08-29',
    dateStatus: 'estimated',
    type: 'trail',
    distances: ['171 km / 10 000 m D+'],
    tags: ['trail', 'ultra', 'europe', 'mountains', 'bucket-list'],
    featured: true,
    location: { city: 'Chamonix-Mont-Blanc', country: 'France', countryCode: 'FR' },
    start: { lat: 45.923611, lon: 6.869444, name: 'Place du Triangle de l’Amitié, Chamonix' },
    fees: [{ amount: 400, currency: 'EUR', indicative: true, label: { en: 'UTMB 171 km entry', pl: 'Opłata za UTMB 171 km' } }],
    website: 'https://montblanc.utmb.world/',
    registrationUrl: 'https://utmb.world/open-registrations',
    links: [{ url: 'https://montblanc.utmb.world/races', label: { en: 'All races of the week', pl: 'Wszystkie biegi tygodnia' } }],
    content: {
      en: {
        summary: 'The world championship of trail running: 171 km and 10,000 m of climbing around Mont Blanc, through France, Italy and Switzerland.',
        description: 'UTMB circles the Mont Blanc massif through three countries, and the fastest runners take just over 19 hours while most spend two nights on the trail. Entry requires Running Stones earned at qualifying UTMB World Series races, then a lottery on top. Race week in Chamonix also hosts CCC, OCC, TDS and PTL, so a start line is realistically reachable at several distances. The 2027 date follows the usual late-August pattern — confirm when the calendar is published.',
      },
      pl: {
        summary: 'Nieoficjalne mistrzostwa świata w biegach górskich: 171 km i 10 000 m przewyższenia wokół Mont Blanc, przez Francję, Włochy i Szwajcarię.',
        description: 'UTMB okrąża masyw Mont Blanc przez trzy kraje — najszybsi pokonują trasę w nieco ponad 19 godzin, większość spędza na szlaku dwie noce. Wejście wymaga zdobycia Running Stones w kwalifikacyjnych biegach UTMB World Series, a następnie wylosowania miejsca. W tygodniu startowym w Chamonix rozgrywane są też CCC, OCC, TDS i PTL, więc realnie można wybrać jeden z kilku dystansów. Data 2027 wynika ze stałego wzorca końca sierpnia — potwierdź po publikacji kalendarza.',
      },
    },
  },
  {
    slug: 'marathon-des-sables',
    name: 'Marathon des Sables',
    date: '2027-04-10',
    endDate: '2027-04-20',
    dateStatus: 'estimated',
    type: 'stage',
    distances: ['~250 km / 6 stages'],
    tags: ['stage', 'ultra', 'desert', 'africa', 'extreme', 'self-supported'],
    featured: true,
    location: { city: 'Ouarzazate, Sahara', country: 'Morocco', countryCode: 'MA' },
    start: { lat: 30.919722, lon: -6.893333, name: 'Sahara bivouac near Ouarzazate (varies yearly)' },
    fees: [{ amount: 5400, currency: 'EUR', indicative: true, label: { en: 'Entry incl. logistics and flights from Europe', pl: 'Pakiet z logistyką i lotami z Europy' } }],
    website: 'https://marathondessables.com/en/',
    links: [{ url: 'https://en.wikipedia.org/wiki/Marathon_des_Sables', label: { en: 'Wikipedia', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: 'Six stages, ~250 km across the Sahara, carrying your own food and sleeping bag in 45 °C heat.',
        description: 'The Marathon des Sables is the archetypal self-supported stage race: runners carry all their food and equipment for the week, with only water rations and a communal bivouac tent provided. One stage is a non-stop long leg of 80–90 km. Sand dunes, dry riverbeds and rocky jebels are covered in daytime temperatures that regularly pass 45 °C. Dates move between spring and winter editions, so verify the exact window with the organiser.',
      },
      pl: {
        summary: 'Sześć etapów, ~250 km przez Saharę, z własnym jedzeniem i śpiworem na plecach, w 45 °C.',
        description: 'Marathon des Sables to wzorcowy bieg etapowy w formule samowystarczalnej: zawodnicy niosą całe jedzenie i wyposażenie na cały tydzień, a organizator zapewnia jedynie racje wody i wspólny namiot w biwaku. Jeden z etapów to długi, nieprzerwany odcinek 80–90 km. Wydmy, wyschnięte koryta rzek i skaliste dżebele pokonuje się w temperaturach regularnie przekraczających 45 °C. Terminy przesuwają się między edycją wiosenną a zimową, więc potwierdź dokładne okno u organizatora.',
      },
    },
  },
  {
    slug: 'great-wall-marathon',
    name: 'Great Wall Marathon',
    date: '2027-05-15',
    dateStatus: 'estimated',
    type: 'road',
    distances: ['42.2 km', '21.1 km', '8.5 km'],
    tags: ['bucket-list', 'asia', 'hilly', 'stairs'],
    featured: false,
    location: { city: 'Huangyaguan, Tianjin', country: 'China', countryCode: 'CN' },
    start: { lat: 40.1075, lon: 117.502778, name: 'Yin and Yang Square, Huangyaguan Great Wall' },
    fees: [{ amount: 1300, currency: 'EUR', indicative: true, label: { en: 'Entry incl. travel package', pl: 'Pakiet startowy z podróżą' } }],
    website: 'https://great-wall-marathon.com/',
    links: [{ url: 'https://en.wikipedia.org/wiki/Great_Wall_Marathon', label: { en: 'Wikipedia', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: '5,164 steps on the Great Wall of China, twice, in May humidity.',
        description: 'The course leaves Yin and Yang Square, climbs onto the Huangyaguan section of the Great Wall, drops into surrounding villages and farmland, then returns to the Wall for a second pass. There are 5,164 steps in total and finishing times run one to two hours slower than a runner’s road marathon. Entries are typically sold as travel packages through official partners rather than as a standalone bib.',
      },
      pl: {
        summary: '5164 stopnie na Wielkim Murze Chińskim, dwa razy, w majowej wilgotności.',
        description: 'Trasa wychodzi z Placu Yin i Yang, wspina się na odcinek Huangyaguan Wielkiego Muru, schodzi do okolicznych wiosek i pól, a następnie wraca na Mur na drugie przejście. Do pokonania jest łącznie 5164 stopni, a czasy na mecie bywają o jedną–dwie godziny gorsze od maratonu ulicznego. Zapisy sprzedawane są zwykle w formie pakietów turystycznych u oficjalnych partnerów, a nie jako sam numer startowy.',
      },
    },
  },
  {
    slug: 'midnight-sun-marathon-tromso',
    name: 'Midnight Sun Marathon',
    date: '2027-06-19',
    dateStatus: 'estimated',
    type: 'road',
    distances: ['42.2 km', '21.1 km', '10 km'],
    tags: ['europe', 'arctic', 'night-race', 'scenic'],
    featured: false,
    location: { city: 'Tromsø', country: 'Norway', countryCode: 'NO' },
    start: { lat: 69.649167, lon: 18.955833, name: 'Tromsø city centre' },
    fees: [{ amount: 950, currency: 'NOK', indicative: true, label: { en: 'Marathon entry', pl: 'Opłata za maraton' } }],
    website: 'https://msm.no/en/',
    links: [{ url: 'https://en.wikipedia.org/wiki/Midnight_Sun_Marathon', label: { en: 'Wikipedia', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: 'A marathon started at 20:30 inside the Arctic Circle, run in full daylight at midnight.',
        description: 'Tromsø sits 350 km north of the Arctic Circle, and in late June the sun simply does not set. The marathon starts in the evening so that runners cross the Tromsø Bridge and the island coastline in bright night light, with the Lyngen Alps across the water. Cool temperatures near 10 °C make it a surprisingly comfortable race despite the unusual hour.',
      },
      pl: {
        summary: 'Maraton ze startem o 20:30 za kołem podbiegunowym, biegany w pełnym świetle o północy.',
        description: 'Tromsø leży 350 km na północ od koła podbiegunowego, a pod koniec czerwca słońce po prostu nie zachodzi. Maraton startuje wieczorem, dzięki czemu most Tromsø i wybrzeże wyspy pokonuje się w jasnym nocnym świetle, z widokiem na Alpy Lyngen po drugiej stronie fiordu. Chłodne, około 10-stopniowe warunki sprawiają, że mimo nietypowej pory biegnie się zaskakująco komfortowo.',
      },
    },
  },
  {
    slug: 'maraton-warszawski',
    name: 'Maraton Warszawski',
    date: '2026-09-27',
    dateStatus: 'estimated',
    type: 'road',
    distances: ['42.2 km'],
    tags: ['road', 'europe', 'poland'],
    featured: false,
    location: { city: 'Warszawa', country: 'Poland', countryCode: 'PL' },
    start: { lat: 52.231944, lon: 21.005833, name: 'Plac Defilad' },
    fees: [{ amount: 220, currency: 'PLN', indicative: true, label: { en: 'Standard entry', pl: 'Opłata standardowa' } }],
    website: 'https://maratonwarszawski.com/',
    links: [{ url: 'https://pl.wikipedia.org/wiki/Maraton_Warszawski', label: { en: 'Wikipedia (PL)', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: 'Poland’s biggest marathon: a September loop through central Warsaw and across the Vistula.',
        description: 'The Warsaw Marathon is the largest race of its kind in Poland, drawing well over 10,000 runners through the city centre, Praga on the right bank of the Vistula, and back past the Palace of Culture. The course is flat with a handful of bridge ramps, and late September usually delivers good running temperatures. Verify the exact date and start location with the organiser, as both have shifted between editions.',
      },
      pl: {
        summary: 'Największy maraton w Polsce: wrześniowa pętla przez centrum Warszawy i przez Wisłę.',
        description: 'Maraton Warszawski to największy bieg tej rangi w Polsce — na trasę przez centrum, prawobrzeżną Pragę i z powrotem obok Pałacu Kultury wyrusza grubo ponad 10 000 biegaczy. Trasa jest płaska, z kilkoma podjazdami na mosty, a koniec września zwykle daje dobre warunki do biegania. Dokładną datę i miejsce startu potwierdź u organizatora — obie rzeczy zmieniały się między edycjami.',
      },
    },
  },
  {
    slug: 'cracovia-maraton',
    name: 'Cracovia Maraton',
    date: '2027-04-11',
    dateStatus: 'estimated',
    type: 'road',
    distances: ['42.2 km'],
    tags: ['road', 'europe', 'poland', 'scenic'],
    featured: false,
    location: { city: 'Kraków', country: 'Poland', countryCode: 'PL' },
    start: { lat: 50.06465, lon: 19.944979, name: 'Rynek Główny / Aleje Trzech Wieszczów' },
    fees: [{ amount: 200, currency: 'PLN', indicative: true, label: { en: 'Standard entry', pl: 'Opłata standardowa' } }],
    website: 'https://www.cracoviamaraton.pl/',
    links: [{ url: 'https://pl.wikipedia.org/wiki/Cracovia_Maraton', label: { en: 'Wikipedia (PL)', pl: 'Wikipedia' } }],
    content: {
      en: {
        summary: 'A spring marathon through one of Europe’s best-preserved medieval city centres.',
        description: 'Cracovia Maraton runs past Wawel Castle, through the Kazimierz quarter and around the Old Town, with a finish traditionally on the Main Market Square. April weather is variable but usually cool enough for a fast time, and the historic backdrop makes it one of the most photogenic marathons in Central Europe. Confirm the date, which moves within the first half of April.',
      },
      pl: {
        summary: 'Wiosenny maraton przez jedno z najlepiej zachowanych średniowiecznych centrów Europy.',
        description: 'Cracovia Maraton prowadzi obok Wawelu, przez Kazimierz i wokół Starego Miasta, a meta tradycyjnie znajduje się na Rynku Głównym. Kwietniowa pogoda bywa zmienna, ale zwykle jest wystarczająco chłodno na dobry czas, a historyczna sceneria czyni z niego jeden z najbardziej fotogenicznych maratonów Europy Środkowej. Potwierdź termin — bieg przesuwa się w obrębie pierwszej połowy kwietnia.',
      },
    },
  },
];

export async function fetchEvents() {
  const now = new Date().toISOString();
  return EVENTS.map((event) => ({
    ...event,
    source: { id, url: event.website ?? null, ref: event.slug, fetchedAt: now },
  }));
}
